/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Zenghua.Zhang' at '16-9-14 上午9:14' with Gradle 2.14.1
 *
 * @author Zenghua.Zhang, @date 16-9-14 上午9:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
